// This file is generated by `cargo run --bin gen-api-types`. Do not edit manually.

export type FieldScores = { title: number; headings: number; tags: number; content: number };

export type NoteResponse = { content: string; mtime: number; tags: Array<string>; title: string };

export type SaveResult = {
  mtime: number;
  path?: string;
  title?: string;
  updated?: Array<string>;
  conflict?: boolean;
  content?: string;
};

export type SearchHit = {
  path: string;
  title: string;
  tags: Array<string>;
  excerpt: string;
  score: number;
  field_scores: FieldScores;
};

export type NoteEntry = { path: string; title: string; tags: Array<string> };

export type TagListResponse = { tags: Array<string> };

export type FileSearchResult = { path: string; title: string };

export type RecentFileEntry = { path: string; title: string; mtime: number };

export type PinnedFileEntry = { path: string; title: string };

export type RenameResponse = { path: string; title: string; updated: Array<string> };

export type FilenameResponse = { filename: string };

export type ContentResponse = { content: string };

export type OkResponse = { ok: boolean };

export type PutNoteRequest = { content: string; expected_mtime: number };

export type CreateNoteRequest = { content: string };

export type RenameRequest = { old_path: string; new_path: string };

export type PinRequest = { path: string };

export type SessionState = {
  tabs?: Array<string>;
  active?: number;
  closed?: Array<string>;
  cursors?: { [key in string]: number };
};

export type AppStatus = {
  locked: boolean;
  encrypted: boolean;
  needs_setup: boolean;
  prf_credential_ids: Array<string>;
  prf_credential_names: Array<string>;
};

export type VaultEntry = {
  index: number;
  name: string;
  active: boolean;
  encrypted: boolean;
  locked: boolean;
};

export type UnlockRequest = { recovery_key?: string; prf_key?: string };

export type PrfRegisterRequest = { credential_id: string; prf_key: string; name: string };

export type PrfRemoveRequest = { credential_id: string };

export type Settings = {
  weight_title: number;
  weight_headings: number;
  weight_tags: number;
  weight_content: number;
  fuzzy_distance: number;
  recency_boost: number;
  result_limit: number;
  show_score_breakdown: boolean;
  excluded_folders: Array<string>;
};
