export const TEST_IDS = {
  contextMenu: '[data-ui="context-menu"]',
  contextMenuItem: '[data-ui="context-menu-item"]',
  tab: '[data-ui="tab"]',
  activeTab: '[data-ui="tab"][data-active="true"]',
  newTab: '[data-ui="tab-new"]',
  tabClose: '[data-ui="tab-close"]',
  tabDirty: '[data-ui="tab-dirty"]',
  tabLabelText: '[data-ui="tab-label-text"]',
  tabTooltip: '[data-ui="tab-tooltip"]',
  navFile: '[data-ui="nav-file"]',
  activeNavFile: '[data-ui="nav-file"][data-active="true"]',
  navFileName: '[data-ui="nav-file-name"]',
  navFileText: '[data-ui="nav-file-text"]',
  navFileDir: '[data-ui="nav-file-dir"]',
  navFileTime: '[data-ui="nav-file-time"]',
  navEmpty: '[data-ui="nav-empty"]',
  vaultSelect: '[data-ui="vault-select"]',
} as const;
